version: "3.2"

services:
  #
  # Backend Services
  #

  # Postgres database (dev)
  postgres:
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: gripedotdev
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations/:/docker-entrypoint-initdb.d/
      - ./db/test_data.sql:/docker-entrypoint-initdb.d/test_data.sql
    networks:
      - postgres_network

  # in-browser SQL GUI (dev, optional)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - postgres_network
    depends_on:
      - postgres

  # GraphQL API
  graphql:
    image: graphile/postgraphile:4
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://gripedotdev:password@postgres/gripedotdev
    networks:
      - postgres_network
    depends_on:
      - postgres

  #
  # Frontend Services
  #
  webapp:
    image: gripedotdev/webapp
    build: .
    ports:
      - 4200:80
    depends_on:
      - graphql

networks:
  postgres_network:

volumes:
  postgres_data:
